### ISSUE TITLE
How to add a custom OID? 

### ISSUE THREAD

**Issue by schneim** [okba-zoueghi/X.509-utility#2]
How can one add a custom OID under extensions:

Say OID 1.2.3.4.5.6.7.8 shall have the value of 1011011101000000b (16bit)

**Comment by okba-zoueghi** [comment]
Since the utility is based on OpenSSL and OpenSSL reads the extensions' configuration statically from a config file, it's not possible to support generating custom extensions with custom OIDs from the CLI. However you can adjust the config files and add a definition to your custom extension, you should also adjust the scripts to use the newly defined extension.
You could have a look at this link (https://www.openssl.org/docs/man1.0.2/man5/x509v3_config.html). It is documented how to add an arbitrary extension  a user chosen OID.

**Comment by schneim** [comment]
Thanks Okba. I was able to add the OID in the config file.

**Comment by okba-zoueghi** [comment]
Great, how did you achieve that? Did you do as I described above, or did you follow another appoach?

**Comment by schneim** [comment]
Yep, like you described it.
